language: python
python:
  - "2.7"
  - "3.7"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: python PyTest/test/pytest.py
